image: alpine

before_script:
  # - apt update && apt -y install make autoconf flex bison build-essential
  - apk update && apk add make autoconf flex bison build-base

build:
  stage: build
  script:
    - make

build_tests:
  stage: build
  script:
    - make tests
