image: alpine

build:
  stage: build
  before_script:
    # - apt update && apt -y install make autoconf flex bison build-essential
    - apk update && apk add make autoconf flex bison build-base
  script:
    - make && make tests
